"""
Django settings for django-test project.
Generated by 'django-admin startproject' using Django 3.2.5.
"""

import os
from dotenv import load_dotenv
from pathlib import Path

# 📦 Charger les variables d'environnement (.env)
load_dotenv()

# 📁 Base du projet
BASE_DIR = Path(__file__).resolve().parent.parent

# 🔐 Clé secrète (à garder secrète en prod !)
SECRET_KEY = os.getenv("SECRET_KEY", "fallback-secret-if-missing")

# ✅ DEBUG activé en dev, désactivé en prod
DEBUG = True  # ⚠️ à passer à False en production

ALLOWED_HOSTS = ['*']  # À restreindre en prod

# 📦 Apps
INTERNAL_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

CUSTOM_APPS = [
    'users',
    'products',
    'favourites',
    'home',
    'cart',  # 👈 Ajoute ton app panier ici si ce n’est pas déjà fait
]

THIRD_PARTY_APPS = [
    'phonenumber_field',
]

INSTALLED_APPS = INTERNAL_APPS + CUSTOM_APPS + THIRD_PARTY_APPS

# 🧩 Middlewares
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'get_user.RequestMiddleware',
]

ROOT_URLCONF = 'Project.urls'

# 🎨 Templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Project.wsgi.application'

# 🗄️ Base de données
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# 🔐 Sécurité des mots de passe
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# 🌍 Internationalisation
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# 📁 Fichiers statiques & médias
STATIC_URL = '/static/'
MEDIA_URL = '/media/'

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'assets')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 🧱 Autres réglages
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 🔐 Authentification
LOGIN_URL = '/user/login/'
LOGIN_REDIRECT_URL = '/home/'
LOGOUT_REDIRECT_URL = '/home/'
