name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Node.js dependencies (Cypress and others)
        run: |
          npm install

      - name: Start Django server
        run: |
          python manage.py migrate
          nohup python manage.py runserver 0.0.0.0:8000 &
          sleep 10

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v5
        with:
          start: npm start  # Ce n'est pas nécessaire ici, alors on le retire
          wait-on: http://localhost:8000
          wait-on-timeout: 60
