name: Run Cypress Tests

on:
  push:
    branches:
      - main   # Exécuter sur chaque push dans main
  pull_request:
    branches:
      - main   # Et aussi sur chaque pull request vers main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Utilise Python 3

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Version Node.js recommandée

      - name: Install Cypress
        run: |
          npm install

      - name: Start Django server
        run: |
          python manage.py migrate
          nohup python manage.py runserver 0.0.0.0:8000 &
          sleep 10  # Attendre que le serveur démarre

      - name: Run Cypress tests
        run: |
          npx cypress run
