name: DAST ZAP Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zap_scan:
    name: OWASP ZAP Baseline Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'https://python-app-171565716676.europe-west1.run.app'
          cmd_options: '-t 1 -J report.json -w report.md -r report.html'

      - name: Upload ZAP reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: |
            report.json
            report.md
            report.html
