name: Trivy Image Scan

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  trivy-scan:
    name: Run Trivy vulnerability scanner
    runs-on: ubuntu-latest
    continue-on-error: true  # ✅ le job ne fait pas échouer le pipeline

    steps:
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y

      - name: Trivy Scan Docker Image
        env:
          TRIVY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          TRIVY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "$TRIVY_PASSWORD" | docker login -u "$TRIVY_USERNAME" --password-stdin
          trivy image --severity HIGH,CRITICAL ngnepiepaye/isen-python:dev-d4fe53aa74a164bb37bd083266c34c666893bdc0

